# This contains params to be used by the stages to train or predict
Data_preprocessing:
  ner_tags:
    - O
    - B-PER
    - I-PER
    - B-ORG
    - I-ORG
    - B-LOC
    - I-LOC

Base_model_config:
  base_model_name: xlm-roberta-base
  num_classes : 7
  num_epochs: 1
  batch_size: 16
  save_steps: 100000

Predict_model_config:
  truncation: True
  is_split_into_words: True
