# It contains all the configs required in the project

paths:
  artifacts: artifacts
  data_store: data
  logs: logs
  model_weight: model_weight
  serialized_objects: serialized_objects

data_ingestion_config:
  dataset_name: xtreme
  subset_name: PAN-X.en

data_validation_config:
  data_split:
    - train
    - test
    - validation

  type_check:

  null_check:

  columns_check:
    - tokens
    - ner_tags
    - langs
